copySrc:
	ssh jaouent@muse-login.meso.umontpellier.fr "rm -rf /home/jaouent/scratch/Src/ChangementClimatique_Bottet2019/CodesTristan/8_RunsEtudeFrance_ApresCorrectionNcdfLH_MESO/Src_CTRIP/*"
	scp -r ./../../8_RunsEtudeFrance_ApresCorrectionNcdfLH_MESO/Src_CTRIP/*  jaouent@muse-login.meso.umontpellier.fr:/home/jaouent/scratch/Src/ChangementClimatique_Bottet2019/CodesTristan/8_RunsEtudeFrance_ApresCorrectionNcdfLH_MESO/Src_CTRIP/
